export const SET_BOOKS_LOADING = "SET_BOOKS_LOADING";
export const BOOKS_LOADING_SUCCESS = "BOOKS_LOADING_SUCCESS";
export const BOOKS_LOADING_FAILURE = "BOOKS_LOADING_FAILURE";
export const STORE_CONFIG = "STORE_CONFIG";
